---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/css $DEPLOYPATH/js $DEPLOYPATH/assets
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/bash -c "[ -f .htaccess ] && /bin/cp -f .htaccess $DEPLOYPATH || true"
